uncefact/spec-untp

- website/docs/specification/DigitalProductPassport.md
In this PR, I have removed the DPP API spec from the schema table (see [this comment](https://github.com/uncefact/spec-untp/pull/41#discussion_r1538164337)) and updated the example DPP render viewer link as it was pointing to a stale DPP with bad Transformation Event input links.
**DPP Schema Table**
**Example DPP Table**
> chore: update dpp render link

- website/docs/specification/Identifiers.md
Verifying an identifiers doesn't make sense, removing this empty header.
> Removing an out of place header

- untp-v1.jsonld
This adds a limited LD context to the published pages. Should be available from `https://uncefact.github.io/untp-v1`. 
It is far from complete and must be further built out, potentially with tooling. Sharing this very early version is also meant to build the team's understanding of working with LD. This includes basing term definitions on UN in combination with other prevalent vocabs. 
Obviously github.io is an unacceptable domain for any of what we do, not least our context. 
Note it merges into `gh-pages` which probably also is not how we want to maintain in the long run.
> DPP Context

- website/docs/specification/ConformityCredential.md
Addresses issues:
#100 #91 #47 
Changes:
- Move `issuedBy` to `issuer` field of VC
- Remove `issuedTo` and instead have the `credentialSubject` be the issued to entity and shift the attestation into a `hasAttestation` property, similar to https://schema.org/hasCertification.
- Move the evidence field of the `ConformityAttestation` to the evidence field of the VC, defining an evidence type of `ConformityAttestationEvidence`.
- Delegate the `status` field of the `ConformityAttestation` to the `credentialStatus` component of the VCDM (BitstringStatusList).
- Replace the concept of the facility of the assessment with a location.
- Replace terms `subjectProducts` and `subjectFacilities` with `attestedProducts` and `attestedLocations`
- Add new UNTP context file
I will keep this PR scoped to …
> CC schema/example update proposal

- website/untp-v1.jsonld
Addresses some discussions in issue: 
#109
@zachzeus @nissimsan I added the base objects for the CC credential and a suggestion to remove the UNTP prefix for the types as this is now defined by the spec/vocab. If we prefer to keep the prefix it can be added back.
Main goal is to add placeholders for the CC stuff since it's what I'm working on. I also suggested an alphabetical order for the defined types and creating url links at the top of the context so we don't have to paste the complete url everywhere.
What is the long term goal for this context?
What will its relationship be with the other contexts:
https://test.uncefact.org/vocabulary/untp/cc/ca-context.jsonld
https://test.uncefact.org/vocabulary/untp/dpp/dpp-context.jsonld
> UNTP context: Re-order alphabetically, create url links, add CC objects

- website/docs/specification/VerifiableCredentials.md
The text says that the W3C spec is called Verifiable Credentials. I know I'm being pedantic (occupational hazard) but it's called Verifiable Credentials Data Model. The acronym VC is used extensively in the doc and then, towards the end, we see VCDM. I've made a couple of very minor edits to, I hope, reduce confusion.
I've also undated the reference to the GS1 Web Voc which, horror or horrors, we're moving to a different namespace after 14 years (so we can manage it more easily in line with our other change-controlled docs on ref.gs1.org).
> Minor pedantic points about name of W3C spec

- website/samples/untp-digital-product-passport-v0.3.10.json
This fixes these three bad commas. 
All the syntax rearranging happens on the github side. I don't know why or how to avoid it. Annoying. But the three commas are the only substantial changes of this.
> fix: json syntax bugs

- website/extensions/index.js
- website/implementations/Certifiers.js
- website/implementations/Industry.js
- website/implementations/Registers.js
- website/implementations/Regulators.js
- website/implementations/Software.js
- website/implementations/index.js
- website/package.json
- website/src/components/Pledges/index.tsx
- website/src/components/Pledges/styles.module.css
- website/src/css/index.css
- website/src/pages/index.js
- website/src/types/css.d.ts
- website/src/types/index.ts
- yarn.lock
This PR adds a reusable carousel component and implements it on the homepage to showcase UNTP implementation pledges. When a user clicks on an image in the carousel, it navigates the user to the corresponding pledge page (see Transmute Example) below.
**IMPORTANT NOTE**: PR #223 needs to be merged first.
https://github.com/user-attachments/assets/2a469547-89d0-4a92-944d-fb9c6b69d091
https://github.com/user-attachments/assets/a2e7852a-3ef7-4094-b5f5-fcdefb6a1338
> feat: pledge carousel

- website/src/components/ScrollToHash/index.tsx
- website/src/theme/Root.js
This PR adds a smooth scroll navigation component that automatically scrolls to matching element IDs in URLs. For example: clicking a link to /spec-untp/docs/implementations/Software#freshchain will smoothly scroll to the freshchain section.
https://github.com/user-attachments/assets/ced31e8d-4628-4a82-a3e6-8c4fabd45c11
> feat: scroll to id

- website/components/YouTube.tsx
- website/docs/about/index.md
Note: Feel free to ignore this - just documenting my own experience with suggestions that would have improved it.
When I started reading about UNTP on the about page, I loved the first paragraph, then headed for the next link, the short presentation.
Reading the short presentation without any other background caused me to spend a lot of time trying to parse the info and diagrams without a lot of context.
If I'd first watched the video (even though I normally prefer to read - I could have also read below) the same information would have been presented with a lot more context.
So... this PR does 3 things:
1. Moves the "Presentations & Videos" section to the end (more relevant after reading the about if I then want to use the presentation info, not so useful without more context), but
2. …
> About: Move presentations (pdf/ppx) to end of about. Embed Vid.

- website/docs/specification/VerifiableCredentials.md
This PR seeks to simplify the requirements for Verifiable Credentials within UNTP by requiring exclusive support for [VCDM v2](https://www.w3.org/TR/vc-data-model-2.0/). 
The context for this matter can be found in ticket #262.
> fix(vc)!: require exclusive support for VCDM v2

- .github/workflows/docs-to-pdf.yml
This PR adds the missing `fs-extra` dependency and required Puppeteer args, which prevented the pipeline from succeeding and publishing the PDF artefact.
A [PR](https://github.com/jean-humann/docs-to-pdf/pull/484) has been raised to address the issue upstream.
**Docs to PDF**
Workflow run: https://github.com/uncefact/spec-untp/actions/runs/13230989915
Artefact produced: https://github.com/uncefact/spec-untp/commit/f70f859d76df03cf79058bb4880a42dece9fdc7a#diff-b490d7ed59ca3e8e3a79beb07ba889e726ecae899d848e536fd5c8d72c849329
> fix: add missing dependency

- .github/workflows/docs-to-pdf.yml
This PR excludes the pages associated with the implementation register from the pdf derived from the website.
Artefact produced: https://github.com/uncefact/spec-untp/blob/d4b01a26cad5332f4ce17c368ef34bc13fedb287/website/static/un-transparency-protocol.pdf
Context: https://uncefact.slack.com/archives/C03L1LDU1ED/p1739249948701249
> ci: exclude implementation register

- .github/workflows/docs-to-pdf.yml
This PR adjusts the text size within the pdf derived from the website.
**Note**: There are h1 tags being misused on some of the pages, which will be rectified in another PR.
**Previous**
**New**
**Previous**
**New**
Artefact produced: [un-transparency-protocol-new-text-size.pdf](https://github.com/user-attachments/files/18748300/un-transparency-protocol.3.pdf)
Context: https://uncefact.slack.com/archives/C03L1LDU1ED/p1739249948701249
> ci: update pdf text size

- website/docs/specification/DigitalFacilityRecord.md
It's called `Digital Facility Record` everywhere else, fixing the title for consistency
> Inconsistent Facility title

- docs/untp-data-model/changes-v0.6.0-beta4.md
Adds history of change for 0.6.0-beta4, related to supporting rendering property.
> doc: Add change history for 0.6.0-beta4

- .github/actions/validate-jargon-artefacts/src/config.js
- .github/actions/validate-jargon-artefacts/src/contextValidation.js
- .github/actions/validate-jargon-artefacts/src/index.js
This PR fixes #313 and also addresses a secondary issue that was hidden by the primary problem.
As described in #313, the validation pipeline was incorrectly validating all instances in the payload, not just the primary sample instance. Secondary instances lacking a `@context` caused the pipeline to fail when the JSON-LD processor attempted to expand them.
I've introduced a `JARGON_INSTANCES_TO_VALIDATE` variable that explicitly lists which sample instance names should be validated.
The code now filters the payload to validate only those named instances, ignoring all others within the JSON-LD expansion step. 
This approach was chosen because:
- The instance order is not guaranteed.
- There is no identifier marking the “primary” instance.
- The primary instance’s name is user-defined and …
> fix: skip validation of secondary instances without context

- website/docs/specification/DigitalIdentityAnchor.md
The property `verifiedDIDList` was removed during the initial development of the DIA after [@PatStLouis recommended sticking with just the `credentialSubject.id` ](https://github.com/uncefact/spec-untp/pull/200#discussion_r1829741129). This reference remained and confuses readers (like me :) ).
One related question (not blocking this PR): AIUI, the subject of the DIA should be the DID of the issuer of the DPP/DCC (as outlined originally in https://github.com/uncefact/spec-untp/issues/56 but also [now in the `did:webvh` spec](https://identity.foundation/didwebvh/v1.0/#the-whois-use-case)). Although we are doing so here by ensuring the DIA.credentialSubject.id is the did of the DPP/DCC issuer, we also appear to be mixing types. That is, in the DPP, the issuer did is a `CredentialIssuer`, …
> Remove reference to property `verifiedDIDList` deleted 6 months ago.

- website/docs/specification/ConformityCredential.md
- website/docs/specification/DigitalFacilityRecord.md
- website/docs/specification/DigitalIdentityAnchor.md
- website/docs/specification/DigitalProductPassport.md
- website/docs/specification/DigitalTraceabilityEvents.md
This PR fixes #67 by extending the documentation for each UNTP data model to include the location of its ontology and instructions for retrieval.
> feat: add retrieval instructions for ontologies

- data-models/untp-core/vocabulary.jsonld
Update the description of CredentialIssuer.id since did:tdw was renamed to did:webvh.
See https://jargon.sh/user/unece/untp-core/issue/1
> chore: sync untp-coredata model with Jargon snapshot 7

- data-models/untp-core/artefacts/context.jsonld
Update `mimeType` codetable link, removing `allTypes` as the external examples follow the pattern `https://mimetype.io/application/atom+xml` so the join of the mimeType is just with the root address.
Similarly, update unitOfMeasure codetable link, appending a `#` since the external examples follow the pattern `https://vocabulary.uncefact.org/UnitMeasureCode#10`
Note: Jargon uses the URL both for concatenating with a value for an ID and for displaying to the user as the link where they can see all values, but it can't work for both always. This change gives priority to the former (valid and usable jsonld, with possibly incorrect link in JSONSchema description to users). See https://github.com/jargon-sh/issues/issues/52
> Fix `mimeType` and `unitOfMeasure` external code table links so they concatenate with values

- .github/actions/validate-jargon-artefacts/src/contextValidation.js
This PR addresses the issue described in issue #369 by enforcing stricter validation when expanding documents.
I've swapped `jsonld.expand` for `jsonld.toRDF` as the expansion method is allowing errors to slip through (see issue [#570](https://github.com/digitalbazaar/jsonld.js/issues/570)), but are not when using the toRDF method (see issue [#369](https://github.com/uncefact/spec-untp/issues/369#issuecomment-2878387214)).
The toRDF method first expands the document in safe mode (using the options passed in to the toRDF method) and then converts the expanded document to RDF (see code [here](https://github.com/digitalbazaar/jsonld.js/blob/71656073c2abe14b2538215ec8592cd9548b7a35/lib/jsonld.js#L668)).
``` bash
docker run --rm -e INPUT_JARGON-WEBHOOK-PAYLOAD='{"action":{"name":"onSnapshot","t …
```
> fix: use jsonld.toRDF for stricter validation

- .github/actions/validate-jargon-artefacts/src/contextValidation.js
This PR resolves an issue in the [artifact validation action](https://github.com/uncefact/spec-untp/tree/main/.github/actions/validate-jargon-artefacts), where the action crashes if the context array of the sample instance being validated contains an object (see this [workflow run](https://github.com/uncefact/spec-untp/actions/runs/15153318094/job/42603315863)).
I’ve added a type guard to check if the value is a string. If it is, the transformation proceeds (as described in PR #359); otherwise, the transformation is skipped.
``` bash
docker run --rm -e INPUT_JARGON-WEBHOOK-PAYLOAD='{"action":{"name":"onSnapshot","type":"snapshot"},"artefacts":{"dataModel":{"fileName":"unece_SustainabilityVocabulary_dataModel.svg","url":"https://jargon.sh/user/unece/SustainabilityVocabulary/s/19/artefacts/d …
```
> fix: account for objects in context

- website/src/components/Pledges/index.tsx
- website/src/types/index.ts
This PR extends the `Implementations` interface to include image size, which the Pledges carousel then consumes.
This addresses an issue where SVGs inherently lack a size, resulting in a size of 0x0px and avoids placing a constraint on other logos displayed that don't share the same aspect ratio.
Rendering of an SVG
**Before the fix**
**After the fix**
> feat: pass image size to carousel

- .github/workflows/data-models-snapshot.yml
- .github/workflows/jargon-release.yml
- .github/workflows/validate-jargon-artefacts.yml
This PR updates workflows to be triggered for PRs with main branch as a base instead of data-models-staging.
It also adds an additional job to validate artefacts if the PR is a release one.
> feat: run validation for PRs with main as a base
