uncefact/spec-untp

website/docs/about/Goals.md
Proposed change to answer #28 - doesn't address the questions and discussion that Nis and Chris were having.
=> Update Goals.md to describe depth of supply applicability question.

website/docs/specification/VerifiableCredentials.md
Implement discussion in issue #31   closes #31
=> Update Verifiable Credentials section

website/docs/about/Meetings.md, website/docs/design-patterns/index.md
from design patterns to best practices. Also name meetings correctly
=> fix titles

website/docs/specification/DigitalProductPassport.md
This PR updates the DPP example substantially:
1. adds example values instead of types (like "string")
2. aligns the credential to the VC data model
3. adds a bunch of LD (assumes "id": "@id" and "type": "@type")
4. exemplifies a referenced context
5. links to conformity credentials instead of having them embedded
Pls consider this incremental improvement, I'm not suggesting this to be a final model at all; we have much more to discuss and improve on this still.
=> DPP example update

website/docs/specification/DigitalProductPassport.md, website/samples/untp-digital-product-passport.json, website/schema/untp-digital-product-passport-schema.0.5.0.json
1. Adds JSON schema corresponding to the latest DPP example
2. References the context added on https://github.com/uncefact/spec-untp/pull/102
=> DPP schema and context reference

website/docs/specification/VerifiableCredentials.md
Recommendations are fine, but demanding a particular rendering method is beyond what we are here to do.
=> MAY rendering method

website/docs/about/index.md
fixed the "prootcol" typo, noticed one other sentence to fix
=> fix "protocol" typo, minor text tweaks for clarity

website/docs/implementations/Regulators.md
Fix typo
`tensure` should be `tenure`
=> Fix Typo in Update Regulators.md

website/docs/implementations/Industry.md, website/docs/implementations/Registers.md, website/docs/implementations/Regulators.md, website/docs/implementations/Software.md
This PR fixes Markdown formatting for tables and subheadings to ensure proper display.
=> chore: fix formatting issues

website/docs/business-case/BusinessCaseIndustry.md
Update to Business case industry with links and added content
=> Luca - updated to business case industry page

website/docs/business-case/BusinessCaseIndustry.md
Fixing small "vary" homophone typo on `BusinessCaseIndustry.md`
=> minor BusinessCaseIndustry homophone fix

docs/untp-data-model/changes-v0.6.0-beta1.md
Documentation only. Feel free to point out or fix any typos, but otherwise, please land so I can include the link in my update.
Thanks :)
=> doc: Adds detailed changes between 0.6.0-alpha2 and 0.6.0-beta1.

docs/untp-data-model/changes-v0.6.0-beta1.md, docs/untp-data-model/changes-v0.6.0-beta5.md
=> doc: Add changes for the 0.6.0-beta5 release.

docs/untp-data-model/changes-v0.6.0-beta10.md
See https://github.com/absoludity/spec-untp/blob/add-0.6.0-beta10-notes/docs/untp-data-model/changes-v0.6.0-beta10.md
=> doc: Add release notes for 0.6.0-beta10

data-models/untp-dte/artefacts/AggregationEvent-instance.json, data-models/untp-dte/artefacts/AggregationEvent-schema.json, data-models/untp-dte/artefacts/AssociationEvent-instance.json, data-models/untp-dte/artefacts/AssociationEvent-schema.json, data-models/untp-dte/artefacts/DigitalTraceabilityEvent-instance.json, data-models/untp-dte/artefacts/DigitalTraceabilityEvent-schema.json, data-models/untp-dte/artefacts/ObjectEvent-instance.json, data-models/untp-dte/artefacts/ObjectEvent-schema.json, data-models/untp-dte/artefacts/TransactionEvent-instance.json, data-models/untp-dte/artefacts/TransactionEvent-schema.json, data-models/untp-dte/artefacts/TransformationEvent-instance.json, data-models/untp-dte/artefacts/TransformationEvent-schema.json, data-models/untp-dte/artefacts/context.jsonld, data-models/untp-dte/vocabulary.jsonld
chore: testing snapshot webhook
=> chore: sync traceabilityEventsdata model with Jargon snapshot 3

data-models/untp-dpp/artefacts/DigitalProductPassport-instance.json, data-models/untp-dpp/artefacts/DigitalProductPassport-schema.json, data-models/untp-dpp/artefacts/ProductPassport-instance.json, data-models/untp-dpp/artefacts/ProductPassport-schema.json, data-models/untp-dpp/artefacts/context.jsonld, data-models/untp-dpp/vocabulary.jsonld
Update `ProductPassport.traceabilityInformation` to be an array. As per https://github.com/uncefact/spec-untp/issues/190
=> chore: sync DigitalProductPassportdata model with Jargon snapshot 0

data-models/untp-dcc/artefacts/ConformityAttestation-instance.json, data-models/untp-dcc/artefacts/ConformityAttestation-schema.json, data-models/untp-dcc/artefacts/DigitalConformityCredential-instance.json, data-models/untp-dcc/artefacts/DigitalConformityCredential-schema.json, data-models/untp-dcc/artefacts/context.jsonld, data-models/untp-dcc/vocabulary.jsonld
Added ConformityAssessment.name as per https://github.com/uncefact/spec-untp/issues/190
=> chore: sync ConformityCredentialdata model with Jargon snapshot 0

data-models/untp-dia/artefacts/DigitalIdentityAnchor-instance.json, data-models/untp-dia/artefacts/DigitalIdentityAnchor-schema.json, data-models/untp-dia/artefacts/RegisteredIdentity-instance.json, data-models/untp-dia/artefacts/RegisteredIdentity-schema.json, data-models/untp-dia/artefacts/context.jsonld, data-models/untp-dia/vocabulary.jsonld
Sync domain with spec-untp repo
=> chore: sync DigitalIdentityAnchordata model with Jargon snapshot 0

data-models/untp-dfr/artefacts/DigitalFacilityRecord-instance.json, data-models/untp-dfr/artefacts/DigitalFacilityRecord-schema.json, data-models/untp-dfr/artefacts/FacilityRecord-instance.json, data-models/untp-dfr/artefacts/FacilityRecord-schema.json, data-models/untp-dfr/artefacts/context.jsonld, data-models/untp-dfr/vocabulary.jsonld
Sync domain with spec-untp repo
=> chore: sync DigitalFacilityRecorddata model with Jargon snapshot 0

data-models/untp-core/artefacts/context.jsonld, data-models/untp-core/vocabulary.jsonld
Sync domain with spec-untp repo (take 3..)
=> chore: sync untp-coredata model with Jargon snapshot 5

data-models/untp-core/artefacts/context.jsonld
Add trailing hash to countryCode external vocab.
See https://github.com/uncefact/spec-untp/issues/369#issuecomment-2878387214 for details.
=> chore: sync untp-coredata model with Jargon snapshot 6

website/docs/governance/adoptionGroup.md, website/docs/governance/conformityGroup.md
Added them to the adoption group page and moved the TOR for the conformity page.
Closes #463 and #464
=> Made changes to the Terms of reference.  
